import * as parser from "@babel/parser";
import { walk } from "estree-walker";
import type { JSXElement, Node } from "@babel/types";

type ParsedComponent = {
  id: string;
  parent: string | null;
  props: Record<string, string>;
};

export function parseReactComponents(code: string): ParsedComponent[] {
  const ast = parser.parse(code, {
    sourceType: "module",
    plugins: ["jsx", "typescript"],
  });

  const components: ParsedComponent[] = [];

  function extractJSX(node: JSXElement, parent: string | null = null): void {
    const opening = node.openingElement;

    if (opening.name.type !== "JSXIdentifier") {
      return;
    }

    const name = opening.name.name;

    const props: Record<string, string> = {};

    for (const attr of opening.attributes) {
      if (attr.type !== "JSXAttribute") {
        continue;
      }

      if (attr.name.type !== "JSXIdentifier") {
        continue;
      }

      const key = attr.name.name;

      if (!attr.value) {
        props[key] = "true";
        continue;
      }

      if (attr.value.type === "StringLiteral") {
        props[key] = attr.value.value;
        continue;
      }

      if (attr.value.type === "JSXExpressionContainer") {
        const expr = attr.value.expression;

        if (expr.type === "Identifier") {
          props[key] = expr.name;
        } else {
          props[key] = expr.type;
        }
      }
    }

    components.push({
      id: name,
      parent,
      props,
    });

    for (const child of node.children) {
      if (child.type === "JSXElement") {
        extractJSX(child, name);
      }
    }
  }

  walk(ast, {
    enter(node: Node) {
      if (
        node.type === "ReturnStatement" &&
        node.argument &&
        node.argument.type === "JSXElement"
      ) {
        extractJSX(node.argument);
      }
    },
  });

  return components;
}
// Parser generated by ChatGPT